### ISSUE TITLE
Support compiler remappings

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape-solidity#14]
Related to this: https://github.com/ApeWorX/ape/issues/149

This is the other side of getting github dependencies to work for simple projects

*Desired Example Config Syntax*

```
dependencies:
  open_zeppelin: OpenZeppelin/openzeppelin-contracts@4.4.0

solidity:
  remapping:
    - "@openzeppelin=open_zeppelin"
```
