### ISSUE TITLE
Allow libraries to be listed in config

### ISSUE THREAD

**Issue by antazoey** [ApeWorX/ape-solidity#140]
### Overview

`.add_library` is great for pre-compile scripts but it'd be nice to have a way to list the libraries in the `ape-config.yaml` file as well.

### Specification

```yaml
solidity:
  libraries:
    ethereum:
      mainnet:
        MyLibrary: 0x003123012312412541241241242   # pretend is address
```

And then (not sure about this next part): Have `compile()` detect if we are connected to a provider and if the network matches anything we have listed in `libraries:` and if it does, grab those addresses and add the libraries.

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.
