### ISSUE TITLE
Issues using Slither on .cache directory

### ISSUE THREAD

**Issue by antazoey** [ApeWorX/ape-solidity#62]
### Environment information

Latest ape and plugin

* Python Version: 3.9.7
* OS: macOS

### What went wrong?

It has been reported that it is challenging to run Slither on the `.cache` directory from dependencies.

### How can it be fixed?

Not sure! We should experiment with Slither and consider integrating with the tool more officially.

**Comment by unparalleled-js** [comment]
@ca11ab1e

**Comment by ca11ab1e** [comment]
Here is how I did it (it take hours to find a working process).

## Ape-specific

Content of `ape-config.yml`:

```yml
dependencies:
  - name: OpenZeppelinSolidity
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.6.0

solidity:
  import_remapping:
    - "@openzeppelin/contracts=OpenZeppelinSolidity/4.6.0"
```

In order to have OZ contracts downloaded, I did `ape compile`.

## Other

Slither will use hardhat to compile contracts, but I didn't find a way to expose the remapping. So I'll force usage of `solc` later.

First, we need to download the proper `solc` binary:

```bash
SOLIDITY_VERSION_IN_USE="$(/bin/grep 'pragma solidity' ${SOLIDITY_PATH}/myContract.sol | awk '{print $3}' | tr -d ';')"
SOLC_FOLDER="$HOME/.solc"
SOLC_BIN="solc-${SOLIDITY_VERSION_IN_USE}"

setup_or_update_solc() {
    local solc_path="${SOLC_FOLDER}/${SOLC_BIN}"

    if ! test -f "${solc_path}" ; then
        local url="https://github.com/ethereum/solidity/releases/download/v${SOLIDITY_VERSION_IN_USE}/solc-static-linux"
        mkdir -p "${SOLC_FOLDER}"
        curl -L "${url}" -o "${solc_path}"
    fi

    if ! test -x "${solc_path}"; then
        chmod a+x "${solc_path}"
    fi
}
```

Then, calling Slither as follow will work:

```bash
analyze_sol() {
    setup_or_update_solc

    slither \
        --compile-force-framework 'solc' \
        --solc "${SOLC_FOLDER}/${SOLC_BIN}" \
        --solc-remaps '@openzeppelin/contracts=contracts/.cache/OpenZeppelinSolidity/v4.6.0' \
        'contracts/solidity'
}
```
